### ISSUE TITLE
Do not calulate age if year is 1604 or alternatively older as a certain value

### ISSUE THREAD

**Issue by Vipale** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#17]
1604 seems to be apples workaround if no birthyear is set. So no age should be calculated.
Alternatively you could add an option to the settings to define a year and if a birthyear is before that no age is calculated.

**Comment by rsjtdrjgfuzkfg** [comment]
Can't you just remove the year 1604 in Thunderbird and thus clean up your address book? I think this should ideally be fixed globally. After all, the wrong year does not only affect birthday calendars, but all places where the birth year is displayed / used.

If that is not possible, can you explain why that is the case (how do you sync your address book, when is the 1604 (re-)inserted, etc.)? Depending on where the issue comes from, there might be different ways to fix it.

**Comment by Vipale** [comment]
I thought the exact same third and that's actually what I tried first. Then birthdays were not visible on my iOS calendar anymore.
So I ended up readding 1604 to those contacts.

I am syncing my contacts with nextcloud.

**Comment by rsjtdrjgfuzkfg** [comment]
From a short web search, it seems this is a known bug in iOS. No idea if Apple plans to fix it, though...

As this is a bug in a third-party device (and not related to Thunderbird or this add-on), I'm not sure if it is a good idea to add a workaround in this add-on.

That said, I can see how the workaround might be useful for some people and thus would accept a patch that permits to optionally ignore birth years before a given date.

**Comment by Vipale** [comment]
thank you very much for implementing a workaround

**Comment by myssv** [comment]
When you sync your contacts with Outlook/MS Exchange a year is needed. Therwise it will end with errors.

That's why I use year 1603 for people, where I don't know the year of birth.

**Comment by myssv** [comment]
How can I add the fix?

**Comment by rsjtdrjgfuzkfg** [comment]
@myssv If you are not a developer, you don't need to do anything; the change will be in the next regular release, likely in a few weeks when the first beta versions for Thunderbird 115 are released.

If you are a developer, see https://github.com/rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#building
