### ISSUE TITLE
Birthdays not visible in Mini-Month calendar

### ISSUE THREAD

**Issue by gtoedi** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#2]
Birthdays are displayed correctly in calendar tab and event list. Thank you for replacing the ThunderBirthDay with this.
But in 'Today Pane | Mini-Month Calendar' the related days are not marked bold, as I would expect.

Observed on 
Win 10 (64) - 20H2
Thunderbird 78.4.2 (64 bit)
Birthday Calendar 1.0

**Comment by rsjtdrjgfuzkfg** [comment]
This is intentional and not directly related to the add-on: the view you describe marks all days as bold that have events that mark time as 'busy'. Birthdays – like most all-day events – are transparent for free-busy searches and thus do not cause the date to become bold.

You could think of 'busy' events as the events where you need to be somewhere (physically or virtually), while 'free' events are events that happen without you being personally involved. In Thunderbird, all-day events default to 'free' (= transparent), while all other events default to 'busy'.
