### ISSUE TITLE
Contact synced via Cardbook not show

### ISSUE THREAD

**Issue by schtebo** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#5]
Hi,
thank you for your addon.
I tried it, but my contacts synced via Addon: CardBook sadly not shown in calendar.
It would be so cool, if you could add this support.
With Thunderbird Address book all is fine :)

Thank you very much + BR
schtebo

**Comment by rsjtdrjgfuzkfg** [comment]
CardBook is a completely independent address book application which does not support Thunderbird's address book interfaces – so it is not feasible for other add-ons to interact with it in any meaningful way. If you want to use CardBook, you should use its own feature to display birthdays in the calendar instead of trying to work "against" the intention of the CardBook developers.

Alternatively, you can use a sync add-on for Thunderbird address books, such as GeneralSync (for local network synchronization) or TbSync (for CardDAV and other cloud/server-based synchronization) – and then add birthday calendars using this add-on.
