### ISSUE TITLE
Display name: invalid

### ISSUE THREAD

**Issue by Berndho** [rsjtdrjgfuzkfg/thunderbird-birthdaycalendar#8]
Bestehenden Anzeigename im Adressbuch gelöscht, ergibt im Kalender im Namen Feld irgend einen Platzhalter. 

d027c82b-253f-4b57-8429-9355ff911e0d  <<<<< sollt der Name sein. 
Wann
Montag, 7. Oktober 1985

reproduzierbar durch eintragen und löschen

**Comment by rsjtdrjgfuzkfg** [comment]
Please keep discussions in this repository in English.

_English issue description as I understand it:_ "After deleting the display name of a contact, the birthday calendar displays a placeholder like d027c82b-253f-4b57-8429-9355ff911e0d instead of the name."

----

Yes, if you remove the display name the birthday calender will display the internal id of the contact: that seems better than displaying *nothing*. As you deleted the name, there is no name to display!

I'm glad to reopen if I misunderstood what you're asking about, though?

**Comment by 1u** [comment]
Hi there! Thx for the nice addon! It's very useful to me.

Displaying the contacts id is definitively better than nothing at all.  
I propose to first check fields "first name", "family name" and then / or "email" and display it and only in case they are empty, displaying the id. 

Why: Users can't search contacts IDs in the UI of Thunderbird, they are not able to find out who it is.  
I have several birthdays displayed in my calendar of people with an empty display name field. So I don't know who this id belongs to / who it might be.

**Comment by rsjtdrjgfuzkfg** [comment]
@1u this might be a stupid and tangential question, but how did you get those contacts?

If such contacts are common I can see the value in having a better fallback. I was under the impression that pretty much the only way you can get there is by actively deleting the display name, or by having a contact that truly has no name.

Either way, sounds like a reasonable suggestion, I opened #13 for you.
